name: Laravel

on:
  push:
    branches: [ "dev-ci" ]
  pull_request:
    branches: [ "dev-ci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    #- name: Create Database
    #  run: |
     #   mkdir -p database
      #  touch database/database.sqlite
   # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #  env:
    #    DB_CONNECTION: sqlite
     #   DB_DATABASE: database/database.sqlite
      #run: vendor/bin/phpunit
    #- name: Login to Deployment Server
      #run: sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no ubuntu@54.169.39.205 "pwd" 
    #  run: ssh -p $PASSWORD ubuntu@54.169.39.205
    #- name: Deploy in EC2
    #  env:
    #      PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
    #      HOSTNAME : ${{ secrets.HOSTNAME }}
    #      USER_NAME : ${{ secrets.USER_NAME }}
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > app-test.pem && chmod 600 app-test.pem
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '